#!/bin/bash

module load Subversion

usage ()
{
    echo "Usage: $0 -r <repo_url> <directory_to_import>"
    exit 0
}

while [ -n "$1" ]; do
    while getopts ":r:" OPT; do
        case $OPT in
       	    r)
                if [ -d $OPTARG ]; then
                    REPO_DIR=`readlink -f $OPTARG`
                else
                    echo
                    echo Repository directory \"$OPTARG\" cannot found.
                    exit 1
                fi
                ;;
            \?)
                echo
                echo Invalid option -$OPTARG.
                usage
                ;;
            :)
                echo
                echo Missing argument for -$OPTARG.
                usage
                ;;
            *)
                usage
                ;;
        esac
    done
    if [ $OPTIND == 1 ]; then
        if [ -d $1 ]; then
            IMPORT_DIR=`readlink -f $1`
        else
            echo \"$1\" is not a valid directory. 
            exit 1
        fi
        shift
    else
        shift $((OPTIND-1))
        unset OPTIND
    fi
done

if [ -z "$IMPORT_DIR" ]; then
    echo No directory is specified for import. 
    usage
fi

if [ -z "$REPO_DIR" ]; then
    echo No \"-r\" option is used to specify repository directory. 
    usage
fi

echo Importing \"$IMPORT_DIR\" directory into \"$REPO_DIR\" repository. 

SVN_URL=file://$REPO_DIR

#svn import $IMPORT_DIR
[[ $DEBUG ]] && echo Executing \'svn import $IMPORT_DIR ${SVN_URL}${IMPORT_DIR} -m \"Initial import of $IMPORT_DIR\"\'.
svn import $IMPORT_DIR ${SVN_URL}${IMPORT_DIR} -m "Initial import of $IMPORT_DIR"

if [ $? != 0 ]
then
    echo Error occurs, refer to previous error message for details. 
    exit 1
fi

[[ $DEBUG ]] && echo Executing \'svn checkout --force ${SVN_URL}${IMPORT_DIR} $IMPORT_DIR\'.
svn checkout --force ${SVN_URL}${IMPORT_DIR} $IMPORT_DIR

[[ $DEBUG ]] && echo Executing \'svn -R ps svn:needs-lock ON ${IMPORT_DIR}\'. 
svn -R ps svn:needs-lock ON $IMPORT_DIR
[[ $DEBUG ]] && echo Executing \'svn ci $IMPORT_DIR -m \"set needs-lock properties\"\'. 
svn ci $IMPORT_DIR -m "set needs-lock properties"
